import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ConvexClientProvider from "@/ConvexClientProvider";
import { Toaster } from "@/components/ui/toaster"
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { FileIcon, StarIcon } from "lucide-react";
import Sidenav from "./Sidenav";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
  
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function Dashboardlayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="container mx-auto pt-12">
      <div className="flex gap-8">
        <Sidenav/>
      <div className="w-full">
        {children}
        </div>
      </div>
    </main>
  );
}
